### ISSUE TITLE
Playgrounds Test: Fatal error: Uncaught TypeError: AspirePress_Debug::logData()

### ISSUE THREAD

**Issue by asirota** [aspirepress/AspireUpdate#13]
When using the [playgrounds link](https://playground.wordpress.net/?blueprint-url=https://raw.githubusercontent.com/aspirepress/AspireUpdate/refs/heads/playground-ready/assets/playground/blueprint.json)

With this [blueprint.json](https://github.com/aspirepress/AspireUpdate/blob/playground-ready/assets/playground/blueprint.json)

I get this error on initial settings screen for AP Update 

Getting

`Fatal error: Uncaught TypeError: AspirePress_Debug::logData(): Argument #1 ($type) must be of type string, null given, called in /wordpress/wp-content/plugins/AspireUpdate-playground-ready/classes/AspirePress_Debug.php on line 83 and defined in /wordpress/wp-content/plugins/AspireUpdate-playground-ready/classes/AspirePress_Debug.php:95 Stack trace: #0 /wordpress/wp-content/plugins/AspireUpdate-playground-ready/classes/AspirePress_Debug.php(83): AspirePress_Debug::logData(NULL, 'Target API Foun...') #1 /wordpress/wp-content/plugins/AspireUpdate-playground-ready/aspirepress-updater.php(146): AspirePress_Debug::logString('Target API Foun...', 'string') #2 /wordpress/wp-includes/class-wp-hook.php(3): {closure}(false, Array, 'https://api.wor...') #3 /wordpress/wp-includes/plugin.php(2): WP_Hook->apply_filters(false, Array) #4 /wordpress/wp-includes/class-wp-http.php(3): apply_filters('pre_http_reques...', false, Array, 'https://api.wor...') #5 /wordpress/wp-includes/class-wp-http.php(3): WP_Http->request('https://api.wor...', Array) #6 /wordpress/wp-includes/http.php(2): WP_Http->post('https://api.wor...', Array) #7 /wordpress/wp-includes/update.php(2): wp_remote_post('https://api.wor...', Array) #8 /wordpress/wp-includes/update.php(2): wp_version_check() #9 /wordpress/wp-includes/class-wp-hook.php(3): _maybe_update_core('') #10 /wordpress/wp-includes/class-wp-hook.php(3): WP_Hook->apply_filters(true, Array) #11 /wordpress/wp-includes/plugin.php(2): WP_Hook->do_action(Array) #12 /wordpress/wp-admin/admin.php(2): do_action('admin_init') #13 {main} thrown in /wordpress/wp-content/plugins/AspireUpdate-playground-ready/classes/AspirePress_Debug.php on line 95`

**Comment by asirota** [comment]
I've tried Turning off Ap_debug_mode in config settings in the blueprint.json as well as navigating to standard settings screen by default. I can go into the front end of the site and navigate to the plugin so this is something that happens on initial visit to the settings page of AP Update.
